### ISSUE TITLE
Android: missing callback

### ISSUE THREAD

**Issue by chrisjbrown** [sitefinitysteve/nativescript-auth0#6]
lock.show() generates this error on android. Any idea what I'm missing?

my code
```
lock.show().then((res) => {
        console.log('login success');
    }, function (error) {
        console.log(error);
    });
```

error
```
An uncaught Exception occurred on "OkHttp Dispatcher" thread.
com.google.gson.JsonParseException: Missing required attribute callback
	at com.auth0.android.lock.internal.configuration.GsonDeserializer.requiredValue(GsonDeserializer.java:40)
	at com.auth0.android.lock.internal.configuration.ApplicationDeserializer.deserialize(ApplicationDeserializer.java:51)
	at com.auth0.android.lock.internal.configuration.ApplicationDeserializer.deserialize(ApplicationDeserializer.java:40)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at com.google.gson.Gson.fromJson(Gson.java:887)
	at com.google.gson.Gson.fromJson(Gson.java:852)
	at com.google.gson.Gson.fromJson(Gson.java:801)
	at com.auth0.android.lock.internal.configuration.ApplicationFetcher.parseJSONP(ApplicationFetcher.java:132)
	at com.auth0.android.lock.internal.configuration.ApplicationFetcher.access$100(ApplicationFetcher.java:51)
	at com.auth0.android.lock.internal.configuration.ApplicationFetcher$1.onResponse(ApplicationFetcher```

**Comment by sitefinitysteve** [comment]
Have you looked at the demo app, do you differ much from it?

**Comment by chrisjbrown** [comment]
I'm able to run the demo just fine and authenticate. But when I change the clientId and domain and try and and auth with my auth0 client I get the same error.

So possibly a problem with my auth0 settings. What should I be using for allowed callback urls for development?

**Comment by chrisjbrown** [comment]
Solved! Had to add the correct callback in auth0 settings

```https://YOURDOMAIN.auth0.com/android/org.nativescript.groceries/callback```
