### ISSUE TITLE
template parsing errors

### ISSUE THREAD

**Issue by vance** [sitefinitysteve/nativescript-auth0#9]
I'm not pulling from npm, as I wanted source in my project. so maybe this is just from master?

Template parse errors:
JS: "let-" is only supported on template elements. ("
JS: <StackLayout class="page">
JS:     <ListView [items]="items" class="list-group">
JS:         <ng-template [ERROR ->]let-item="item">
JS:             <Label [nsRouterLink]="['/item', item.id]" [text]="item.name"
JS:           "): ItemsComponent@4:21
JS:
JS: Error: Template parse errors:
JS: "let-" is only supported on template elements. ("
JS: <StackLayout class="page">
JS:     <ListView [items]="items" class="list-group">
JS:         <ng-template [ERROR ->]let-item="item">
JS:             <Label [nsRouterLink]="['/item', item.id]" [text]="item.name"
JS:           "): ItemsComponent@4:21
JS:     at SyntaxError.BaseError [as constructor] (file:///data/data/org.nativescript.auth0test/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js:1595:29)
JS:     at new SyntaxError (file:///data/data/org.nativescript.auth0test/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js:1793:18)
JS:     at TemplateParser.parse (file:///data/data/org.nativescript.auth0test/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js:11210:21)
JS:     at JitCompiler._compileTemplate (file:///data/data/org.nativescript.auth0test/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js:27480:70)
JS:     at file:///data/data/org.nativescript.auth0test/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js:27363:64
JS:     at Set.forEach (native)
JS:     at JitCompiler._compileComponents (file:///data/data/org.nativescript.auth0test/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js:27363:21)
JS:     at createResult (file:///data/data/org.nativescript.auth0test/files/app/tns_modules/@angular/compiler/bundles/compiler.umd.js:27246:21)
JS:     at ZoneDelegate.invoke (file:///data/data/org.nativescript.auth0test/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:190:28)
JS:     at Zone.run (file:///data/data/org.nativescript.auth0test/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:83:43)

**Comment by vance** [comment]
ah, just the /examples directory munging this.
